import streamlit as st
import pandas as pd
import json
import time
from datetime import datetime
from confluent_kafka import Consumer, KafkaError
import plotly.express as px
import uuid

st.set_page_config(
    page_title="Payment Events Dashboard",
    page_icon="📊",
    layout="wide"
)

# Kafka configuration
KAFKA_BROKER = 'localhost:9092'
EVENTS_TOPIC = 'payment-events'
ALERTS_TOPIC = 'payment-alerts'

EVENTS_GROUP_ID = f'dashboard-events-{uuid.uuid4().hex[:8]}'
ALERTS_GROUP_ID = f'dashboard-alerts-{uuid.uuid4().hex[:8]}'

# Initialize session state
if 'events' not in st.session_state:
    st.session_state.events = []
if 'alerts' not in st.session_state:
    st.session_state.alerts = []
if 'events_consumer' not in st.session_state:
    st.session_state.events_consumer = None
if 'alerts_consumer' not in st.session_state:
    st.session_state.alerts_consumer = None
if 'running' not in st.session_state:
    st.session_state.running = False

def create_consumer(topic, group_id):
    """Create Kafka consumer for a specific topic"""
    try:
        consumer = Consumer({
            'bootstrap.servers': KAFKA_BROKER,
            'group.id': group_id,
            'auto.offset.reset': 'earliest',
            'enable.auto.commit': True,
            'session.timeout.ms': 6000,
            'max.poll.interval.ms': 300000
        })
        consumer.subscribe([topic])
        return consumer
    except Exception as e:
        st.error(f"Failed to create consumer for {topic}: {e}")
        return None


def consume_from_topic(consumer, max_messages=100):
    messages = []
    if consumer is None:
        return messages
    
    try:
        for _ in range(max_messages):
            msg = consumer.poll(timeout=0.1)
            
            if msg is None:
                break
            
            if msg.error():
                if msg.error().code() != KafkaError._PARTITION_EOF:
                    st.error(f"Kafka error: {msg.error()}")
                continue
            
            try:
                data = json.loads(msg.value().decode('utf-8'))
                messages.append(data)
            except json.JSONDecodeError as e:
                st.warning(f"Failed to decode message: {e}")
                
    except Exception as e:
        st.error(f"Consumer error: {e}")
    
    return messages


# Dashboard Header
st.title("📊 Real-Time Payment Events Dashboard")
st.markdown("**Flink SQL** classifies events and detects alerts | Dashboard displays results")


# Control buttons
col1, col2, col3 = st.columns([1, 1, 4])
with col1:
    button_label = "⏸️ Pause" if st.session_state.running else "▶️ Start"
    if st.button(button_label, key="start_stop"):
        st.session_state.running = not st.session_state.running
        if st.session_state.running:
            # Create consumers when starting
            if st.session_state.events_consumer is None:
                st.session_state.events_consumer = create_consumer(EVENTS_TOPIC, EVENTS_GROUP_ID)
            if st.session_state.alerts_consumer is None:
                st.session_state.alerts_consumer = create_consumer(ALERTS_TOPIC, ALERTS_GROUP_ID)
        st.rerun()

with col2:
    if st.button("🗑️ Clear Data", key="clear"):
        st.session_state.events.clear()
        st.session_state.alerts.clear()
        st.rerun()

st.markdown("---")

if st.session_state.running:
    st.success("🟢 Live monitoring active - Reading from Kafka topics")
else:
    st.info("⏸️ Monitoring paused - Click 'Start' to begin")

# Consume events and alerts if running
if st.session_state.running:
    new_events = consume_from_topic(st.session_state.events_consumer, max_messages=100)
    if new_events:
        st.session_state.events.extend(new_events)
        st.session_state.events = st.session_state.events[-100:]
    
    # Read alerts from payment-alerts topic (generated by Flink SQL)
    new_alerts = consume_from_topic(st.session_state.alerts_consumer, max_messages=5)
    if new_alerts:
        st.session_state.alerts.extend(new_alerts)
        # Keep only last 5 alerts
        st.session_state.alerts = st.session_state.alerts[-5:]

col1, col2, col3, col4 = st.columns(4)

with col1:
    st.metric("Total Events", len(st.session_state.events))

with col2:
    success_count = sum(1 for e in st.session_state.events if e.get('status') == 'success')
    st.metric("Successful Payments", success_count)

with col3:
    failure_count = sum(1 for e in st.session_state.events if e.get('status') == 'failed')
    st.metric("Failed Payments", failure_count, 
             delta=f"-{failure_count}" if failure_count > 0 else "0",
             delta_color="inverse")

with col4:
    st.metric("Active Alerts", len(st.session_state.alerts))

st.markdown("---")

col_left, col_right = st.columns([2, 1])

with col_left:
    st.subheader("📡 Recent Events")
    
    if len(st.session_state.events) > 0:
        events_df = pd.DataFrame(st.session_state.events)

        display_columns = ['event_id', 'status', 'amount', 'latency_ms', 'service', 'timestamp']
        available_columns = [col for col in display_columns if col in events_df.columns]
        display_df = events_df[available_columns].tail(10)
        st.dataframe(display_df, use_container_width=True, hide_index=True)
        
        st.subheader("📈 Payment Status Distribution")
        if 'status' in events_df.columns:
            status_counts = events_df['status'].value_counts()
            fig = px.pie(
                values=status_counts.values,
                names=status_counts.index,
                title="Success vs Failed",
                color_discrete_map={'success': '#00cc66', 'failed': '#ff4444'}
            )
            st.plotly_chart(fig, use_container_width=True)
        
    else:
        st.info("No events yet. Start the producer to generate events.")

with col_right:
    st.subheader("🚨 Alerts from Flink SQL")
    
    if len(st.session_state.alerts) > 0:
        for alert in reversed(st.session_state.alerts[-5:]):
            severity = alert.get('severity', 'WARNING')
            alert_type = alert.get('alert_type', 'UNKNOWN')
            message = alert.get('message', 'No message')
            service = alert.get('service', 'N/A')
            event_count = alert.get('event_count', 0)
            
            severity_color = "🔴" if severity == 'CRITICAL' else "🟡"
            bg_color = "#ffe6e6" if severity == 'CRITICAL' else "#fff4e6"
            border_color = "red" if severity == 'CRITICAL' else "orange"
            
            with st.container():
                st.markdown(f"""
                <div style='padding: 10px; border-left: 4px solid {border_color}; 
                            background-color: {bg_color}; 
                            margin-bottom: 10px; border-radius: 5px;'>
                    <strong>{severity_color} {alert_type}</strong><br/>
                    {message}<br/>
                    <small>Service: {service} | Events: {event_count}</small>
                </div>
                """, unsafe_allow_html=True)
    else:
        st.success("No alerts - System healthy")


# Footer
st.markdown("---")
st.markdown("""
<div style='text-align: center; color: gray;'>
    <small>
        Events from: <code>payment-events</code> topic<br/>
        Alerts from: <code>payment-alerts</code> topic (classified by Flink SQL)<br/>
        Dashboard updates automatically when running
    </small>
</div>
""", unsafe_allow_html=True)

if st.session_state.running:
    time.sleep(0.5)
    st.rerun()

